-- CRIANDO TABELA CLIENTE NA STAGE AREA
create table ST_CLIENTE(
	CD_CLIENTE INTEGER,
	NOME_CLIENTE VARCHAR(255),
	EMAIL_CLIENTE VARCHAR(255),
	DT_CARGA TIMESTAMP not NULL
);


-- CRIANDO TABELA PRODUTO NA STAGE AREA
create table ST_PRODUTO(
	COD_PRODUTO VARCHAR(255),
	NOME_PRODUTO VARCHAR(255),
	CAT_PRODUTO VARCHAR(255),
	PRECO_PRODUTO numeric(12,4),
	STATUS_PRODUTO VARCHAR(255),
	DT_CARGA TIMESTAMP not NULL
);

-- CRIANDO TABELA VENDA NA STAGE AREA
create table ST_VENDA(
	DT_VENDA DATE,
	COD_VENDA INTEGER,
	COD_PRODUTO VARCHAR(255),
	COD_CLIENTE VARCHAR(255),
	QTD_VENDA INTEGER,
	VL_VENDA NUMERIC(12,4),
	STATUS_VENDA VARCHAR(255),
	DT_CARGA TIMESTAMP not null
);


