-- VERIFICANDO A VERSÃO DO BANCO DE DADOS
SELECT *
FROM "V$VERSION" ;

--VERIFICANMDO AS TABELAS EXISTENTES
SELECT * 
FROM "V$TABLESPACE" ;

-- CRIANDO TABLESPACE
CREATE TABLESPACE TBS_DADOSCURSO
DATAFILE 'C:\app\Administrador\product\21c\database\TBS_DADOSCURSO.DBF' SIZE 100M;

-- ALTERANDO ACESSO PARA CRIAR USUÁRIO
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

-- CRIANDO USUÁRIO 
CREATE USER CURSO
IDENTIFIED BY "123"
DEFAULT TABLESPACE TBS_DADOSCURSO
TEMPORARY TABLESPACE TEMP;

-- CRIAR PERMISSÃO E PRIVILEGIOS PARA ESTE USUARIO (TODAS PERMISSÕES-EM PRODUÇÃO NÃO É RECOMENDADO)
GRANT DBA TO CURSO;

-- PERMITIR QUE USE TODO O ESPAÇO DO BANCO CRIADO DE 100M
GRANT UNLIMITED TABLESPACE TO CURSO;

-- DESABILITAR A OPÇÃO DE EXPIRAR A SENHA
ALTER PROFILE DEFAULT LIMIT PASSWORD_LIFE_TIME UNLIMITED;


